mesosphere/dkp-catalog-applications

helm-repositories/banzaicloud/banzaicloud.yaml, helm-repositories/banzaicloud/kustomization.yaml
Adding the banzai cloud helm repo, for now I kept it specific to the Kafka operator but maybe it should named more generally so it can be reused for other charts in that repo?
=> feat: Add Banzai Cloud Kafka operator repo

services/kafka-operator/0.20.0/defaults/cm.yaml
After looking through the defaults defined on the [koperator chart](https://github.com/banzaicloud/koperator/blob/master/charts/kafka-operator/values.yaml), I think this is the only other addition we need as of right now. Let me know what you think!
=> feat: Update defaults for kafka operator

services/kafka-operator/0.20.0/kafka-operator.yaml, services/spark-operator/1.1.6/spark-operator.yaml, services/zookeeper-operator/0.2.13/zookeeper-operator.yaml
Adding the `HelmRepository` namespace to the `HelmRelease` objects to allow bundle creation via k-cli. This should be a noop, but the bundle creation process requires this.
=> fix: Add namespace in helmreleases

make/ci.mk
We'll need the AWS env vars for the S3 release job
=> ci: Pass through AWS env vars

helm-repositories/banzaicloud/banzaicloud.yaml, helm-repositories/mesosphere-spark-repo/mesosphere-spark-repo.yaml, helm-repositories/pravega/pravega.yaml, services/kafka-operator/metadata.yaml, services/spark-operator/metadata.yaml, services/zookeeper-operator/metadata.yaml
Label HelmRepositories to support helmMirrorUrl substitution.
See https://github.com/mesosphere/kommander/pull/1534 for why this change is needed
=> chore: add label to allow dynamic secret injection

make/release.mk
Updating the image bundle to use the new release path for DKP artifacts
=> build:  Use /dkp/<version> as s3 path for release

make/release.mk
Updating the actual image bundle name according to https://github.com/mesosphere/kommander/pull/1605/files#diff-70acc2689fb0b36f116699b4dd558c7361f4cc683cd8a4dd6f1e559a76e9a674R159
=> build: Make image bundle release name consistent

make/release.mk
This PR adds a target to generate a repo archive for use in air gapped deployments.
=> build: add repo archive target

Dockerfile.ci, Makefile, make/release.mk, make/tools.mk
This PR adds the chart bundle release (removed from the kommander repo in https://github.com/mesosphere/kommander/pull/1682).
=> build: Add chart bundle release targets

.bloodhound.yml, make/validate.mk
Validates the manifests against different Kubernetes versions, configurable in `.bloodhound.yml`.
Jira: https://jira.d2iq.com/browse/D2IQ-88981
=> build: add validation against multiple Kubernetes versions

make/ci.mk, make/tools.mk
release job is using kcli at `main` which bumped go to 1.19. should be simple enough to bump the go version here to stop the errors.
=> [release-2.3] ci: Use go1.19

make/ci.mk, make/tools.mk
release job is using kcli at main which bumped go to 1.19.
=> ci: Use go1.19 (#78)

make/ci.mk, make/tools.mk
release job is using kcli at main which bumped go to 1.19.
=> ci: Use go1.19

make/validate.mk, services/kafka-operator/0.20.0/metadata.yaml, services/kafka-operator/0.20.2/metadata.yaml, services/kafka-operator/0.23.0-dev.0/defaults/cm.yaml, services/kafka-operator/0.23.0-dev.0/defaults/kustomization.yaml, services/kafka-operator/0.23.0-dev.0/kafka-operator.yaml, services/kafka-operator/0.23.0-dev.0/kustomization.yaml, services/kafka-operator/0.23.0-dev.0/metadata.yaml
https://d2iq.atlassian.net/browse/D2IQ-95258
Adds the latest dev version of kafka-operator https://github.com/banzaicloud/koperator/releases/tag/v0.23.0-dev.0 that is compatible with k8s 1.25
=> feat: Add kafka-operator v0.23.0-dev.0

hack/images.yaml, services/zookeeper-operator/0.2.13/metadata.yaml, services/zookeeper-operator/0.2.14/defaults/cm.yaml, services/zookeeper-operator/0.2.14/defaults/kustomization.yaml, services/zookeeper-operator/0.2.14/kustomization.yaml, services/zookeeper-operator/0.2.14/metadata.yaml, services/zookeeper-operator/0.2.14/zookeeper-operator.yaml, services/zookeeper-operator/metadata.yaml
Bumps the zookeeper-operator to chart version `0.2.14` and the image that was built from our fork.
=> feat: Add zookeeper-operator 0.2.14

hack/images.yaml
Adding the images from the new kafka-operator version that was added. I installed on the daily and grabbed all the images that were being used.
=> build: Add kafka images for new version

services/kafka-operator/0.23.0-dev.0/metadata.yaml
The new PDB API is only available in 1.21+, so this version of the kafka operator will work on k8s >=1.21
=> feat: Update kafka k8s version support

hack/images.yaml, services/kafka-operator/0.24.1/defaults/cm.yaml, services/kafka-operator/0.24.1/defaults/kustomization.yaml, services/kafka-operator/0.24.1/kafka-operator.yaml, services/kafka-operator/0.24.1/kustomization.yaml, services/kafka-operator/0.24.1/metadata.yaml
Add a new version of the Kafka operator, v0.24.1. Jira: [D2IQ-97256](https://d2iq.atlassian.net/browse/D2IQ-97256)
Used [new e2e parameter](https://github.com/mesosphere/kommander-e2e/pull/817) to test. `E2E_TEST_PATH=feature/install/suites/kindcluster E2E_MINIMAL_CONFIG=true  E2E_SKIP_CLEANUP=true  E2E_DKP_CATALOG_BRANCH="logg/bump-kafka-0.24.1"  make test.e2e`
[D2IQ-97256]: https://d2iq.atlassian.net/browse/D2IQ-97256?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: Bump Kafka operator to v0.24.1

hack/images.yaml, services/zookeeper-operator/0.2.15/defaults/cm.yaml, services/zookeeper-operator/0.2.15/defaults/kustomization.yaml, services/zookeeper-operator/0.2.15/kustomization.yaml, services/zookeeper-operator/0.2.15/metadata.yaml, services/zookeeper-operator/0.2.15/zookeeper-operator.yaml
Jira: [D2IQ-97257](https://d2iq.atlassian.net/browse/D2IQ-97257)
Bump Zookeeper operator to 0.2.15. Revert to using the upstream image as [our fix has been merged](https://github.com/pravega/zookeeper-operator/issues/428).
Tested using new parameter on E2E tests: `E2E_TEST_PATH=feature/install/suites/kindcluster E2E_MINIMAL_CONFIG=true  E2E_DKP_CATALOG_BRANCH="logg/bump-zookeeper-0.2.15"  make test.e2e`
[D2IQ-97257]: https://d2iq.atlassian.net/browse/D2IQ-97257?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat:Bump zookeeper to 0.2.15

hack/images.yaml, services/zookeeper-operator/0.2.15/defaults/cm.yaml
Bumps kubectl images used by the zk operator install/upgrade hooks
should we also bump this in the previous zk operator versions (like 0.2.14)? if customers upgrade the catalog git repo, they would automatically get this new image 🤔. I'm thinking we should never update previously released versions, wdyt?
=> fix(zookeeper): bump kubectl image used for hooks

make/release.mk, services/kafka-operator/0.24.1/defaults/cm.yaml
Bumps kube-rbac-proxy to v0.14.1
=> fix(kafka): bump kube-rbac-proxy to v0.14.1

hack/images.yaml
copies over the require images for spark-1.1.17
=> chore: rearrange spark images

hack/cve/whitelist.yaml, make/release.mk
Allows control which containers are sent to CVE reporter by app.
=> feat: limit containers send to CVE reporter

.github/workflows/release-airgap-artifacts.yaml, Makefile, make/ci.mk
Let's fix the following problem:
```
(docker image inspect mesosphere/mesosphere/dkp-catalog-applications-ci:73fbedfa0a22d88a7b64f7c5d728706a8c7e94d4 &>/dev/null && echo 'mesosphere/mesosphere/dkp-catalog-applications-ci:73fbedfa0a22d88a7b64f7c5d728706a8c7e94d4 already exists - skipping image build' ) || \
docker pull mesosphere/mesosphere/dkp-catalog-applications-ci:73fbedfa0a22d88a7b64f7c5d728706a8c7e94d4 || \
make ci.docker.build
Error response from daemon: pull access denied for mesosphere/mesosphere/dkp-catalog-applications-ci, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```
https://github.com/mesosphere/dkp-catalog-applications/actions/runs/6242181447/job/16958359076#step:7:18
Also, changing the value of …
=> ci: Add docker credentials

.github/workflows/release-airgap-artifacts.yaml
It seems we cannot use a private gha.
=> ci: Don't use workflow-db

hack/images.yaml, licenses.d2iq.yaml, make/release.mk
This removes the vulnerable Kafka 3.1.2 image (one used by default by `kafka-operator`) from the air-gapped bundle and adds the oldest image not containing relevant CVEs to the bundle.
The side effect is that in airgapped settings `kafka-operator` will not be able to handle KafkaClusters that do not specify an image explicitly (which is not the recommended way to use it and not something we want to continue to support).
=> chore: bundle a newer Kafka image

hack/images.yaml, licenses.d2iq.yaml, services/zookeeper-operator/0.2.15-dkp.1/defaults/cm.yaml
**Testing**
Did an upgrade from 0.2.13 with a running ZK cluster: first of the app, then of the cluster.
=> chore: switch zookeeper-operator to images from our fork

.github/workflows/create-dev-tag.yaml, Makefile, make/repo.mk, make/tools.mk
Now that we are pulling artifacts from tagged releases from dkp-catalog-applications (instead of `main`) to embed in bootstrapper, we need to cut daily dev tags. Looks like previously we were not cutting daily releases in this repo.
=> build: Add daily dev tag job

.github/workflows/create-dev-tag.yaml
Fixes to get the workflow working - ran it manually and main was successfully tagged. Will backport this action to release branches
https://github.com/mesosphere/dkp-catalog-applications/actions/runs/10694529185/job/29646475482
=> build: Fix daily release workflow

.github/workflows/check-licenses.yaml
This will backport the following commits from `main` to `release-2.12`:
- [fix: check-licenses failure (#146)](https://github.com/mesosphere/dkp-catalog-applications/pull/146)
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)
=> fix: check-licenses failure (2.12)

Dockerfile.ci, make/ci.mk, make/tools.mk
Release tooling is failing with https://github.com/mesosphere/dkp-catalog-applications/actions/runs/11078609251/job/30787951147 after bumping kommander cli go version
=> ci: bump dockerfile golang version

helm-repositories/banzaicloud/banzaicloud.yaml, make/release.mk
This will backport the following commits from `main` to `release-2.12`:
- [fix: use mesosphere stable charts repo for kafka-operator (#157)](https://github.com/mesosphere/dkp-catalog-applications/pull/157)
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)
=> fix: use mesosphere stable charts repo for kafka-operator (2.12)

.bloodhound.yml, Dockerfile.ci, helm-repositories/banzaicloud/banzaicloud.yaml, make/ci.mk, make/release.mk, make/tools.mk
This will backport the following commits from `main` to `release-2.8`:
- [fix: use mesosphere stable charts repo for kafka-operator (#157)](https://github.com/mesosphere/dkp-catalog-applications/pull/157)
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)
=> fix: use mesosphere stable charts repo for kafka-operator (2.8)

.bloodhound.yml, Dockerfile.ci, helm-repositories/banzaicloud/banzaicloud.yaml, make/ci.mk, make/release.mk, make/tools.mk
This will backport the following commits from `main` to `release-2.7`:
- [fix: use mesosphere stable charts repo for kafka-operator (#157)](https://github.com/mesosphere/dkp-catalog-applications/pull/157)
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)
=> fix: use mesosphere stable charts repo for kafka-operator (2.7)

hack/cve/whitelist.yaml, hack/images.yaml, licenses.d2iq.yaml, services/kafka-operator/0.25.3/defaults/cm.yaml, services/kafka-operator/0.25.3/defaults/kustomization.yaml, services/kafka-operator/0.25.3/kafka-operator.yaml, services/kafka-operator/0.25.3/kustomization.yaml, services/kafka-operator/0.25.3/metadata.yaml
e2e https://github.com/mesosphere/kommander-e2e/actions/runs/11328987778
Test run:
```
Kommander installation verifying kommander installation and catalog apps Catalog Application should install cleanly: kafka-operator, version 0.25.3, k8s constraint >=1.21 [install, catalog-apps]
/runner/_work/kommander-e2e/kommander-e2e/test/e2e/components/catalogapps/catalogapps.go:110
> Enter [BeforeEach] Catalog Application @ 10/14/24 15:13:11.569
< Exit [BeforeEach] Catalog Application @ 10/14/24 15:13:11.57 (0s)
> Enter [It] kafka-operator, version 0.25.3, k8s constraint >=1.21 @ 10/14/24 15:13:11.57
STEP: App definition should be created @ 10/14/24 15:13:11.57
END STEP: App definition should be created @ 10/14/24 15:13:11.591 (21ms)
STEP: create AppDeployment @ 10/14/24 15:13:11.591
END STEP: …
```
=> chore(kafka-operator): bump kube-oidc-proxy

.pre-commit-config.yaml, hack/images.yaml, licenses.d2iq.yaml, services/kafka-operator/0.25.1/defaults/cm.yaml, services/kafka-operator/0.25.2/defaults/cm.yaml
Jira ticket: https://jira.nutanix.com/browse/NCN-104599
Description: 
feat: update kube-rbac-proxy path on release-2.12
=> feat: update kube-rbac-proxy path on release-2.12
