- services/spark-operator/metadata.yaml
https://jira.d2iq.com/browse/D2IQ-79904
> feat: fix the overview of spark

- helm-repositories/banzaicloud/banzaicloud.yaml
- helm-repositories/mesosphere-spark-repo/mesosphere-spark-repo.yaml
for https://jira.d2iq.com/browse/D2IQ-79902 and https://jira.d2iq.com/browse/D2IQ-81196
> feat: adding WORKSPACE_NAMESPACE substitution var

- README.md
Signed-off-by: karishmagadiya <kgadiya@d2iq.com>
> chore: update the readme based on repo change

- services/spark-operator/1.1.6/defaults/cm.yaml
https://jira.d2iq.com/browse/D2IQ-81192
> feat: default values for spark operator

- services/kafka-operator/metadata.yaml
- services/spark-operator/metadata.yaml
- services/zookeeper-operator/metadata.yaml
https://jira.d2iq.com/browse/D2IQ-82476
Add `workspace` scope to the 3 apps' metadata.yaml. This can be merged in whenever, until the controller update to read in the scope is merged, this scope will just get ignored for now (all apps will still get created in the workspace).
> feat: Add workspace scope to app metadata

- helm-repositories/banzaicloud/banzaicloud.yaml
- helm-repositories/mesosphere-spark-repo/mesosphere-spark-repo.yaml
- helm-repositories/pravega/pravega.yaml
helmMirrorUrl needs to be parametrized in HelmRepositories
> chore: parametrize helmMirrorUrl in helmrepositories

- services/kafka-operator/metadata.yaml
- services/spark-operator/metadata.yaml
- services/zookeeper-operator/metadata.yaml
related to https://github.com/mesosphere/dcos-docs-site/pull/4016/files
> docs: Add note about installation

- services/kafka-operator/0.20.2/defaults/cm.yaml
- services/kafka-operator/0.20.2/defaults/kustomization.yaml
- services/kafka-operator/0.20.2/kafka-operator.yaml
- services/kafka-operator/0.20.2/kustomization.yaml
Release notes: https://github.com/banzaicloud/koperator/releases
Associated PR to add this version to tests: https://github.com/mesosphere/kommander/pull/1423
> chore: add koperator 0.20.2

- services/spark-operator/1.1.17/defaults/cm.yaml
- services/spark-operator/1.1.17/defaults/kustomization.yaml
- services/spark-operator/1.1.17/kustomization.yaml
- services/spark-operator/1.1.17/spark-operator.yaml
https://jira.d2iq.com/browse/D2IQ-84004
> feat: spark-operator 1.1.17

- services/kafka-operator/metadata.yaml
- services/spark-operator/metadata.yaml
- services/zookeeper-operator/metadata.yaml
Address https://jira.d2iq.com/browse/D2IQ-84511 
Blocked until we have airgapped tests in kommander
> feat: add certification labels

- make/release.mk
Resolves https://jira.d2iq.com/browse/D2IQ-87649
> chore: logs published urls for the release

- mergebot-config.json
- services/kafka-operator/metadata.yaml
- services/spark-operator/metadata.yaml
- services/zookeeper-operator/metadata.yaml
https://jira.d2iq.com/browse/D2IQ-88083
> feat: disable deploying multiple operators instances per workspace

- make/release.mk
Remove `.gz` extension from the image bundle. 
https://jira.d2iq.com/browse/D2IQ-90661
> feat: update image bundle extension

- .gitignore
- make/release.mk
https://jira.d2iq.com/browse/D2IQ-90533
add `NOTICES.txt` to airgap chart and image bundles
> build: add attribution file in release targets

- make/release.mk
add the missing space to tar cmd
> build: add missing space

- docs/dev.md
Just some really basic notes about adding new application versions
> docs: Add some notes about adding new versions

- hack/cve/convert-images-json.jq
- hack/cve/push-images.sh
- make/release.mk
JIRA: https://d2iq.atlassian.net/browse/D2IQ-97860
> feat: add cve-reporter integration make target

- .github/workflows/release-airgap-artifacts.yaml
Backporting release workflow to server 2.4 branch
https://d2iq.atlassian.net/browse/D2IQ-99154
> ci: Backport release workflow

- .github/workflows/release-airgap-artifacts.yaml
We have decided that we no longer want our root accounts to be used in aws roles. This pr simply changes the role in the workflow. **Please do not merge this repo** just approve so once we change the role in aws we can merge this pr right after.
If i have missed a workflow please let me know
> ci: change aws role

- hack/cve/whitelist.yaml
- hack/images.yaml
- licenses.d2iq.yaml
- make/release.mk
- services/zookeeper-operator/0.2.15-dkp.1/defaults/cm.yaml
- services/zookeeper-operator/0.2.15-dkp.1/defaults/kustomization.yaml
- services/zookeeper-operator/0.2.15-dkp.1/kustomization.yaml
- services/zookeeper-operator/0.2.15-dkp.1/metadata.yaml
- services/zookeeper-operator/0.2.15-dkp.1/zookeeper-operator.yaml
Tested manually that the chart works, including upgrade.
> chore: switch from an unmaintained kubectl image to the Bitnami one

- services/kafka-operator/metadata.yaml
- services/zookeeper-operator/metadata.yaml
Add Licensing Tiers for DKP Catalog Applications.
JIRA: https://jira.nutanix.com/browse/NCN-100668
> feat: Add licensing tiers to Kommander Apps

- .github/workflows/release-airgap-artifacts.yaml
- hack/cve/convert-images-json.jq
- make/release.mk
Rename the bundle artifacts produced to NKP. Some variables were renamed.
JIRA: https://jira.nutanix.com/browse/NCN-100952
> feat: Rename DKP artifacts to NKP

- .github/workflows/release-airgap-artifacts.yaml
Fix the DKP bundle steps. The parameter needs to be passed on to the subtask run in Docker.
Jira: https://jira.nutanix.com/browse/NCN-101189
> build: Update where the DKP_OR_NKP_PREFIX is passed

- .github/workflows/create-dev-tag.yaml
- Makefile
- make/repo.mk
- make/tools.mk
backport daily dev release job
> build: Add daily dev tag job (2.7)

- .github/workflows/create-dev-tag.yaml
- Makefile
- make/repo.mk
- make/tools.mk
backport daily dev release job
> build: Add daily dev tag job (2.8)

- .github/workflows/create-dev-tag.yaml
- Makefile
- make/repo.mk
- make/tools.mk
backport daily dev release job
> build: Add daily dev tag job (2.12)

- hack/cve/whitelist.yaml
- hack/images.yaml
- licenses.d2iq.yaml
- services/kafka-operator/0.25.2/defaults/cm.yaml
- services/kafka-operator/0.25.2/defaults/kustomization.yaml
- services/kafka-operator/0.25.2/kafka-operator.yaml
- services/kafka-operator/0.25.2/kustomization.yaml
- services/kafka-operator/0.25.2/metadata.yaml
backport PR https://github.com/mesosphere/dkp-catalog-applications/pull/145
> fix: cve fix for kafka and jmx-javaagent (#145)

- Dockerfile.ci
- make/ci.mk
- make/tools.mk
> ci: bump dockerfile golang version

- .bloodhound.yml
Working for Jira Request https://jira.nutanix.com/browse/NCN-102253
Adding new version of k8s new version for dip-catalog
> feat: update k8s new version to dkp-catalog

- helm-repositories/banzaicloud/banzaicloud.yaml
- make/release.mk
JIRA: https://jira.nutanix.com/browse/NCN-103003
> fix: use mesosphere stable charts repo for kafka-operator

- .bloodhound.yml
https://jira.nutanix.com/browse/NCN-103093
> build: Bump k8s 1.29 version to 1.29.9

- hack/cve/whitelist.yaml
- hack/images.yaml
- licenses.d2iq.yaml
- services/zookeeper-operator/0.2.17/defaults/cm.yaml
- services/zookeeper-operator/0.2.17/defaults/kustomization.yaml
- services/zookeeper-operator/0.2.17/kustomization.yaml
- services/zookeeper-operator/0.2.17/metadata.yaml
- services/zookeeper-operator/0.2.17/zookeeper-operator.yaml
E2E: https://github.com/mesosphere/kommander-e2e/actions/runs/11346849644/job/31556871376
```
Kommander installation verifying kommander installation and catalog apps Catalog Application should install cleanly: zookeeper-operator, version 0.2.17, k8s constraint >=1.21 [install, catalog-apps]
/runner/_work/kommander-e2e/kommander-e2e/test/e2e/components/catalogapps/catalogapps.go:110
> Enter [BeforeEach] Catalog Application @ 10/15/24 14:38:08.197
< Exit [BeforeEach] Catalog Application @ 10/15/24 14:38:08.197 (0s)
> Enter [It] zookeeper-operator, version 0.2.17, k8s constraint >=1.21 @ 10/15/24 14:38:08.198
STEP: App definition should be created @ 10/15/24 14:38:08.198
END STEP: App definition should be created @ 10/15/24 14:38:08.224 (26ms)
STEP: create AppDeployment @ 10/15/24 …
```
> chore(zookeeper-operator): cve fixes bump

- .pre-commit-config.yaml
- services/kafka-operator/0.25.1/defaults/cm.yaml
- services/kafka-operator/0.25.2/defaults/cm.yaml
Jira ticket: https://jira.nutanix.com/browse/NCN-104599
Description : 
feat: update kube-rbac-proxy path on release-2.13
> feat: update kube-rbac-proxy path on release-2.13

- .pre-commit-config.yaml
- hack/images.yaml
- licenses.d2iq.yaml
- services/kafka-operator/0.25.1/defaults/cm.yaml
Jira ticket: https://jira.nutanix.com/browse/NCN-104599
Description:
feat: update kube-rbac-proxy path on release-2.8
> feat: update kube-rbac-proxy path on release-2.8

- .bloodhound.yml
**What problem does this PR solve?**:
bumping 1.32.0 in dk-catalog for checking incompatible resources
**Which issue(s) does this PR fix?**:
https://jira.nutanix.com/browse/NCN-103535
> feat: update k8s new latest version to dkp-catalog

- .bloodhound.yml
https://jira.nutanix.com/browse/NCN-105344 
bumping k8s upgrade 1.32.2
> feat: k8s 1.32.2 upgrade in bloodhound
